<a href="https://colab.research.google.com/github/jane-kirina/python_for_ds_and_ml_tasks/blob/main/module_2/topic_1/HW_2_1_4_Matrices_%26_vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import libraries
import numpy as np

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [ ]:
vector_uniform = np.random.uniform(0, 1, 10)
vector_rand = np.random.rand(10)

matrix = np.array([
    [11, 14, 17],
    [20, 23, 26],
    [29, 32, 35]
])

print(f'Вектор створений через `np.random.uniform`: \n{vector_uniform}')
print(vector_uniform)
print(f'Розмір: {vector_uniform.shape}\n')

print(f'Вектор створений через `np.random.rand`: \n{vector_uniform}')
print(vector_uniform)
print(f'Розмір: {vector_uniform.shape}\n')

print("\nMatrix:")
print(matrix)
print(f'Розмір: {matrix.shape}')

Вектор створений через `np.random.uniform`: 
[0.48596315 0.36692331 0.32247592 0.08629602 0.83616926 0.54187383
 0.55923027 0.51960389 0.33320851 0.72436981]
[0.48596315 0.36692331 0.32247592 0.08629602 0.83616926 0.54187383
 0.55923027 0.51960389 0.33320851 0.72436981]
Розмір: (10,)

Вектор створений через `np.random.rand`: 
[0.48596315 0.36692331 0.32247592 0.08629602 0.83616926 0.54187383
 0.55923027 0.51960389 0.33320851 0.72436981]
[0.48596315 0.36692331 0.32247592 0.08629602 0.83616926 0.54187383
 0.55923027 0.51960389 0.33320851 0.72436981]
Розмір: (10,)


Matrix:
[[11 14 17]
 [20 23 26]
 [29 32 35]]
Розмір: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [ ]:
vector_plus_10 = np.round(vector_rand + 10, 2)
matrix_x_2 = matrix * 2
vector_squared = vector_rand ** 2

print(f'Оригінальний вектор: \n{vector_rand}\n')

print('Додайте до кожного значення вектора vector число 10 і округліть кожне значення до 2 знаків після коми без використання циклів')
print(f'Результат: \n{vector_plus_10}')

print('Помножте кожен елемент матриці з першого завдання на 2 без використання циклів')
print(f'Результат: \n{matrix_x_2}')

print('Створіть новий вектор, який містить квадрат кожного vector без циклів')
print(f'Результат: \n{vector_squared}')








Оригінальний вектор: 
[0.85094867 0.49888022 0.66719847 0.29102126 0.12303661 0.89101999
 0.44694607 0.50183659 0.63472078 0.84966708]

Додайте до кожного значення вектора vector число 10 і округліть кожне значення до 2 знаків після коми без використання циклів
Результат: 
[10.85 10.5  10.67 10.29 10.12 10.89 10.45 10.5  10.63 10.85]
Помножте кожен елемент матриці з першого завдання на 2 без використання циклів
Результат: 
[[22 28 34]
 [40 46 52]
 [58 64 70]]
Створіть новий вектор, який містить квадрат кожного vector без циклів
Результат: 
[0.72411364 0.24888147 0.4451538  0.08469338 0.01513801 0.79391663
 0.19976079 0.25183996 0.40287047 0.72193414]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [ ]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [ ]:
# Task 1
result_matrix  = A @ B
# matrix_dot_product_numpy = np.dot(A, B) # через numpy
print(result_matrix)
print(f'Форма - {result_matrix.shape}')

[[0.232  0.1627 0.2145]
 [0.3061 0.4867 0.633 ]
 [0.1393 0.2261 0.294 ]]
Форма - (3, 3)


In [ ]:
# Task 2
np.dot(result_matrix, C)

ValueError: shapes (3,3) and (2,1) not aligned: 3 (dim 1) != 2 (dim 0)

> Множення неможливе, тому що внутрішні розмірності не збігаються (3 != 2)

In [ ]:
# Task 3
np.dot(result_matrix, D)

ValueError: shapes (3,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

> 3×3 @ 2×2 — внутрішні розміри не збігаються


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [ ]:
# Task 1
matrix_T = result_matrix.T
print(matrix_T)
print(matrix_T.shape)

print(f'Форма - {matrix_T.shape}')

[[0.232  0.3061 0.1393]
 [0.1627 0.4867 0.2261]
 [0.2145 0.633  0.294 ]]
(3, 3)
Форма - (3, 3)


In [ ]:
# Task 2
vector_T = vector_uniform.T
print(vector_T)
print(f'Форма - {vector_uniform.shape}')
print(f'Форма T - {vector_T.shape}')


[0.48596315 0.36692331 0.32247592 0.08629602 0.83616926 0.54187383
 0.55923027 0.51960389 0.33320851 0.72436981]
Форма - (10,)
Форма T - (10,)


> 1D-масив не має осей “рядок/стовпець”
> - `vector` — це просто список чисел
> - `np.T` нічого не міняє, бо нема що міняти місцями

In [ ]:
# Task 3

column_vector = np.expand_dims(vector_uniform, axis=1)
print(f'Форма column_vector - {column_vector.shape}')
print(f'Форма vector_uniform - {vector_uniform.shape}')

Форма column_vector - (10, 1)
Форма vector_uniform - (10,)


> `expand_dims` додає нову вісь і тепер це вектор-стовпець

In [ ]:
# Task 4
column_vector_T = column_vector.T
print(column_vector_T)
print(f'Форма - {column_vector.shape}')
print(f'Форма T - {column_vector_T.shape}')

[[0.48596315 0.36692331 0.32247592 0.08629602 0.83616926 0.54187383
  0.55923027 0.51960389 0.33320851 0.72436981]]
Форма - (10, 1)
Форма T - (1, 10)
